// <auto-generated />
using System;
using BUTR.CrashReportServer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BUTR.CrashReportServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230401192915_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BUTR.CrashReportServer.Models.Database.FileEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<byte[]>("DataCompressed")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("data_compressed");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified");

                    b.Property<long>("SizeOriginal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_original");

                    b.HasKey("Name")
                        .HasName("file_entity_pkey");

                    b.ToTable("file_entity", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
