// <auto-generated />
using System;
using BUTR.CrashReport.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BUTR.CrashReport.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241009200831_NewMetadata")]
    partial class NewMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.HtmlEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<byte[]>("DataCompressed")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data_compressed");

                    b.HasKey("CrashReportId")
                        .HasName("file_entity_pkey");

                    b.ToTable("file_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.IdEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.HasKey("CrashReportId");

                    b.HasIndex("FileId");

                    b.ToTable("id_test_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.JsonEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.HasKey("CrashReportId");

                    b.ToTable("json_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.ReportEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<byte>("Tenant")
                        .HasColumnType("smallint")
                        .HasColumnName("tenant");

                    b.Property<byte>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("CrashReportId");

                    b.ToTable("id_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.HtmlEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("Html")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.HtmlEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.IdEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.HtmlEntity", null)
                        .WithOne("Id")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.IdEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BUTR.CrashReport.Server.Models.Database.JsonEntity", null)
                        .WithOne("Id")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.IdEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("Id")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.IdEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.JsonEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("Json")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.JsonEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.HtmlEntity", b =>
                {
                    b.Navigation("Id");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.JsonEntity", b =>
                {
                    b.Navigation("Id");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.ReportEntity", b =>
                {
                    b.Navigation("Html");

                    b.Navigation("Id");

                    b.Navigation("Json");
                });
#pragma warning restore 612, 618
        }
    }
}
