// <auto-generated />
using System;
using BUTR.CrashReport.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BUTR.CrashReport.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626083614_CanonicalFileIdAndAliases")]
    partial class CanonicalFileIdAndAliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("BUTR:CrashReportInsertFunction:Enabled", true)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.CrashReportInsertResult", b =>
                {
                    b.Property<bool>("Created")
                        .HasColumnType("boolean")
                        .HasColumnName("o_created");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("o_file_id");

                    b.Property<byte>("Tenant")
                        .HasColumnType("smallint")
                        .HasColumnName("o_tenant");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.HtmlEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<byte[]>("DataCompressed")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data_compressed");

                    b.HasKey("CrashReportId")
                        .HasName("html_entity_pkey");

                    b.ToTable("html_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.IdAliasEntity", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<byte>("Tenant")
                        .HasColumnType("smallint")
                        .HasColumnName("tenant");

                    b.HasKey("FileId")
                        .HasName("id_alias_entity_pkey");

                    b.HasIndex("CrashReportId");

                    b.HasIndex("FileId", "Tenant")
                        .IsUnique()
                        .HasDatabaseName("id_alias_entity_file_id_tenant_idx");

                    b.ToTable("id_alias_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.JsonEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.HasKey("CrashReportId");

                    b.ToTable("json_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.OldHtmlEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<byte[]>("DataCompressed")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data_compressed");

                    b.HasKey("CrashReportId")
                        .HasName("old_html_entity_pkey");

                    b.ToTable("old_html_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.ReportEntity", b =>
                {
                    b.Property<Guid>("CrashReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crash_report_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("DeleteTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("delete_token_hash");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<byte>("Tenant")
                        .HasColumnType("smallint")
                        .HasColumnName("tenant");

                    b.Property<byte>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("CrashReportId")
                        .HasName("report_entity_pkey");

                    b.HasIndex("FileId", "Tenant")
                        .IsUnique()
                        .HasDatabaseName("report_entity_file_id_tenant_idx");

                    b.ToTable("report_entity", (string)null);
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.HtmlEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("Html")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.HtmlEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_entity_html_entity_fkey");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.IdAliasEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithMany("Aliases")
                        .HasForeignKey("CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_entity_id_alias_entity_fkey");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.JsonEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("Json")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.JsonEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_entity_json_entity_fkey");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.OldHtmlEntity", b =>
                {
                    b.HasOne("BUTR.CrashReport.Server.Models.Database.ReportEntity", "Report")
                        .WithOne("OldHtml")
                        .HasForeignKey("BUTR.CrashReport.Server.Models.Database.OldHtmlEntity", "CrashReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_entity_old_html_entity_fkey");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BUTR.CrashReport.Server.Models.Database.ReportEntity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Html");

                    b.Navigation("Json");

                    b.Navigation("OldHtml");
                });
#pragma warning restore 612, 618
        }
    }
}
