name: Encrypt Secrets (PowerShell Native)

on:
  workflow_dispatch:

jobs:
  encrypt-secrets:
    runs-on: windows-latest
    steps:
      - name: Encrypt secrets using PowerShell
        shell: pwsh
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          $key = [Convert]::FromBase64String((ConvertTo-SecureString $env:ENCRYPTION_KEY -AsPlainText -Force | ConvertFrom-SecureString -Key (1..32)))
          $iv = New-Object Byte[] 16
          [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($iv)

          $secrets = @{
            HOST = $env:HOST
            PORT = $env:PORT
            USERNAME = $env:USERNAME
            PASSWORD = $env:PASSWORD
          }

          $output = @()

          foreach ($entry in $secrets.GetEnumerator()) {
              $name = $entry.Key
              $plaintext = $entry.Value

              $aes = [System.Security.Cryptography.Aes]::Create()
              $aes.Key = $key
              $aes.IV = $iv
              $aes.Mode = "CBC"
              $aes.Padding = "PKCS7"

              $encryptor = $aes.CreateEncryptor()
              $bytes = [System.Text.Encoding]::UTF8.GetBytes($plaintext)
              $encrypted = $encryptor.TransformFinalBlock($bytes, 0, $bytes.Length)
              $base64 = [Convert]::ToBase64String($encrypted)
              $output += "$name=$base64"
          }

          # Save IV separately for decryption
          [IO.File]::WriteAllLines("secrets.enc", $output)
          [IO.File]::WriteAllText("iv.txt", [Convert]::ToBase64String($iv))

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets
          path: |
            secrets.enc
            iv.txt
